name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Process Changesets
        id: changesets
        uses: changesets/action@v2.1.2
        with:
          publish-script: bun run build && bun x changeset publish --no-git-tag
          pr-title: "Pending Releases"
          commit-message: "chore: update changelog and release"
          github-token: ${{ secrets.BUAPEBOT_SECRET }}
          push-with-git-cli: false
